<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create Baseline Images - All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>bd0fd756-21fd-4e62-8827-34539128cb40</testSuiteGuid>
   <testCaseLink>
      <guid>d5143289-1676-4951-ad42-a1746e3426e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Rangle Website/Visual Test Cases/VTC - Create Baseline Image</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e024ac9d-5f99-46c0-a3d5-7eebdba3f921</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Website Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e024ac9d-5f99-46c0-a3d5-7eebdba3f921</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pageName</value>
         <variableId>e1487eaf-633d-4b71-b89b-49da1b3d6eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e024ac9d-5f99-46c0-a3d5-7eebdba3f921</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nestedLocation</value>
         <variableId>5e6dfab3-1130-47a7-8d7f-f06d40a12ceb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e024ac9d-5f99-46c0-a3d5-7eebdba3f921</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>acceptableDiff</value>
         <variableId>246fabd7-93dd-4cab-b735-633509d748a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebaf7b21-dea3-41a2-8d87-b8648300d516</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
