<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8d2269b0-9f09-4a1b-9e51-004f75d7c29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div[2]/div[2]/div/div/div/div/div/div/section/div/div/div[2]/div/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▼</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;sc-bwzfXH kpGlqZ&quot;]/div[@class=&quot;sc-bwzfXH cdWHmU&quot;]/div[1]/div[1]/div[@class=&quot;sc-bwzfXH dDeNMR&quot;]/div[@class=&quot;sc-bwzfXH uTxCW&quot;]/div[@class=&quot;sc-bwzfXH uTxCW&quot;]/div[@class=&quot;sc-bwzfXH jBXvPt&quot;]/section[@class=&quot;sc-bwzfXH fOfcEO&quot;]/div[@class=&quot;sc-bwzfXH dwOWBY&quot;]/div[@class=&quot;sc-bwzfXH dJhrqB&quot;]/div[@class=&quot;sc-bwzfXH hFUbDu&quot;]/div[@class=&quot;sc-bwzfXH bhCdBG&quot;]/div[@class=&quot;sc-bwzfXH heiDv&quot;]/div[@class=&quot;sc-eqIVtm bCvPnw sc-bwzfXH gxBwGg&quot;]/div[@class=&quot;sc-bwzfXH gtCYMH&quot;]/form[1]/div[@class=&quot;sc-bwzfXH gSheIK&quot;]/div[@class=&quot;sc-bwzfXH uTxCW&quot;]/div[@class=&quot;sc-bwzfXH fffUut&quot;]/div[@class=&quot;sc-bwzfXH fffUut&quot;]/div[@class=&quot;sc-ckVGcZ jlldVh sc-bwzfXH bjNbdL&quot;]/div[@class=&quot;sc-htpNat dykBQf&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//main[@id='content']/div[2]/div[2]/div/div/div/div/div/div/section/div/div/div[2]/div/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How can we help?'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How can we help?'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project inquiry'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career inquiry'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
